packages:
  - ui
  - module/*/ui
  - module/*/func
  - deploy/corpSetup/c11cloudfront/source/authGuardLambdaEdge
  - deploy/corpSetup/c11cloudfront/source/msalSpa
onlyBuiltDependencies:
  - snyk25h
  - snyk25h6
  - snyk
  - snyk@1.1300.2
  - scarf
  - azure-functions-core-tools
  - esbuild
  - protobufjs
