name: "Deploy Ui"
description: "deploy terraform and application code for main ui"

inputs:
  targetEnvName:
    description: "Target environment name"
    required: true
  envType:
    description: "Environment type (e.g., dev, test, prod)"
    required: true
  deployerObjectId:
    description: "Deployer service principal object ID"
    required: true
  deployerName:
    description: "Deployer service principal name"
    required: false
    default: "github-oidc"

runs:
  using: "composite"
  steps:
    - name: Create env file & echo target name
      working-directory: deploy
      shell: bash
      run: |
        echo "TARGET_ENV_NAME:${{ inputs.targetEnvName }}"
        echo "TARGET_ENV=${{ inputs.targetEnvName }}" >> .env

    - name: Read env file
      shell: bash
      run: cat deploy/.env

    - name: Set deployment environment
      shell: bash
      run: |
        echo "TF_VAR_env_type=${{ inputs.envType }}" >> $GITHUB_ENV
        echo "TF_VAR_deployer_sp_object_id=${{ inputs.deployerObjectId }}" >> $GITHUB_ENV
        echo "TF_VAR_deployer_sp_name=${{ inputs.deployerName }}" >> $GITHUB_ENV

    - name: Run Terraform for Function App env and database security
      working-directory: ui/deploy/env
      shell: bash
      run: |
        node ./deployEnvironment.js --auto-approve

    - uses: actions/download-artifact@v4
      with:
        name: my-artifacts-ui
        path: ui/deploy/code/downloaded-artifacts

    - name: Deploy Application code
      working-directory: ui/deploy/code
      shell: bash
      run: node ./deploy.js  --deployDir ./downloaded-artifacts

    - name: Verify the deployment
      working-directory: ui/deploy/verify
      shell: bash
      run: node ./verifyDeployment.js
