name: "Setup pnpm Environment"
description: "Checkout code, setup pnpm, Node.js, and cache dependencies"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm" # caches node_modules for pnpm projects

    - name: Get pnpm store path
      id: pnpm-store
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
